/**
 * @era/core — the AI turnaround-views feature flags. PURE and CLIENT-SAFE.
 *
 * Turnaround views are flag-gated multi-angle renders of an item's cutout
 * (three-quarter / side / back), generated by an image API and QA'd by Claude
 * vision. This module answers two questions and nothing else: "is the turnaround
 * surface turned on?" and "is it turned on for THIS item's category?" It is a
 * deliberate clone of {@link isEraFeedEnabled} (see `feed-flags.ts`) — same
 * exact-string discipline — kept as its own function so the turnaround gate reads
 * independently of the feed gate and the two can diverge without entangling.
 *
 * Dependency-free (no db, no env loader), so web and mobile client bundles import
 * it through the `@era/core/turnaround-flags` subpath without pulling in the
 * server-tainted barrel. Never throws.
 */

/**
 * Master feature flag for the entire turnaround surface. True ONLY for the exact
 * string 'true' — any other value (unset, '1', 'yes', 'TRUE', a typo) reads as
 * off, so a fat-fingered flag can never half-open the feature. The caller supplies
 * the raw value it gates on: the server reads `env.ERA_TURNAROUND_ENABLED`
 * (server-authoritative — when off, the turnaround API routes 404 and no render
 * job is ever queued), the web client `NEXT_PUBLIC_ERA_TURNAROUND_ENABLED`, the
 * mobile client `EXPO_PUBLIC_ERA_TURNAROUND_ENABLED`. The client flags are
 * COSMETIC (they decide what UI to render); the server flag is the real gate.
 * Never throws.
 */
export function isEraTurnaroundEnabled(flag: string | undefined): boolean {
  return flag === 'true';
}

/**
 * Parses `ERA_TURNAROUND_CATEGORIES` — a comma-separated list of item categories
 * turnaround is allowed for (e.g. "shoes,bag,outerwear") — into a normalized set
 * for membership tests. The master flag {@link isEraTurnaroundEnabled} is the gate
 * that turns the feature ON; this is the OPT-IN narrowing on top of it: unset or
 * blank returns `null`, meaning ALL categories are enabled (no narrowing). A
 * non-empty list restricts the feature to exactly those categories.
 *
 * Entries are trimmed, lowercased, and empties dropped, so " Shoes , , bag " reads
 * as the set {"shoes", "bag"}. The values are validated against the live item
 * category enum at the CALL SITE, not here — core stays db-free and never imports
 * the schema, so a category string that doesn't exist in the enum simply never
 * matches a real item rather than being rejected here. Never throws.
 */
export function enabledTurnaroundCategories(csv: string | undefined): ReadonlySet<string> | null {
  if (csv === undefined) return null;
  const entries = csv
    .split(',')
    .map((entry) => entry.trim().toLowerCase())
    .filter((entry) => entry.length > 0);
  return entries.length > 0 ? new Set(entries) : null;
}

/**
 * Is turnaround enabled for a given item category? `null` (the "all categories"
 * signal from {@link enabledTurnaroundCategories}) always answers true; otherwise
 * this is a set-membership test. The caller lowercases nothing — pass the raw
 * category slug and it is compared against the already-lowercased set. Never
 * throws.
 */
export function isTurnaroundCategoryEnabled(
  category: string,
  categories: ReadonlySet<string> | null,
): boolean {
  return categories === null || categories.has(category);
}
